"""
Gerber File Generation and Validation

Features:
- Generate Gerber RS-274X files
- Excellon drill file generation
- Fabrication drawing generation
- Pick-and-place file generation
- Gerber file validation
- NC drill optimization
- Panel generation
- Fiducial placement
"""

from typing import Dict, Any, List, Optional, Tuple
from dataclasses import dataclass
from enum import Enum
from datetime import datetime
from pathlib import Path
import hashlib
from loguru import logger


class GerberLayer(Enum):
    """Gerber layer types."""
    TOP_COPPER = "gtl"
    BOTTOM_COPPER = "gbl"
    TOP_SOLDERMASK = "gts"
    BOTTOM_SOLDERMASK = "gbs"
    TOP_SILKSCREEN = "gto"
    BOTTOM_SILKSCREEN = "gbo"
    TOP_PASTE = "gtp"
    BOTTOM_PASTE = "gbp"
    BOARD_OUTLINE = "gko"
    DRILL = "drl"
    DRILL_MAP = "drr"


class ApertureType(Enum):
    """Aperture types for Gerber."""
    CIRCLE = "C"
    RECTANGLE = "R"
    OBROUND = "O"
    POLYGON = "P"


@dataclass
class Aperture:
    """Gerber aperture definition."""
    number: int
    type: ApertureType
    size: float  # Diameter for circle, width for rectangle
    hole_diameter: Optional[float] = None
    width: Optional[float] = None  # For rectangle
    height: Optional[float] = None


@dataclass
class GerberCommand:
    """Gerber drawing command."""
    command_type: str  # D01=plot, D02=move, D03=flash
    x: Optional[float]
    y: Optional[float]
    aperture: Optional[int]


@dataclass
class DrillHole:
    """Drill hole specification."""
    x: float
    y: float
    diameter: float
    plated: bool


@dataclass
class Component:
    """Component for pick-and-place."""
    designator: str
    x: float
    y: float
    rotation: float
    side: str  # top or bottom
    part_number: str
    value: str
    package: str


class GerberWriter:
    """Write Gerber RS-274X files."""

    def __init__(self, units: str = "metric"):
        """
        Initialize Gerber writer.

        Args:
            units: Units (metric or imperial)
        """
        self.units = units
        self.apertures: Dict[int, Aperture] = {}
        self.current_aperture: Optional[int] = None
        self.commands: List[str] = []
        logger.info(f"GerberWriter initialized ({units})")

    def start_file(self):
        """Start Gerber file with header."""
        self.commands = []

        # File header
        self.commands.append("G04 Generated by Circuit.AI*")
        self.commands.append(f"G04 Date: {datetime.utcnow().isoformat()}*")

        # Format specification
        # X and Y coordinates: 6 digits total, 4 after decimal
        self.commands.append("%FSLAX46Y46*%")

        # Units
        if self.units == "metric":
            self.commands.append("%MOMM*%")
            self.format = "6.4"  # 6 digits, 4 decimal
        else:
            self.commands.append("%MOIN*%")
            self.format = "6.4"

        # Set absolute coordinates
        self.commands.append("G90*")

        # Set linear interpolation
        self.commands.append("G01*")

    def add_aperture(
        self,
        aperture_id: int,
        aperture_type: ApertureType,
        size: float,
        **kwargs
    ):
        """
        Add aperture definition.

        Args:
            aperture_id: Aperture number
            aperture_type: Aperture type
            size: Size (diameter or width)
            **kwargs: Additional parameters (width, height, hole_diameter)
        """
        aperture = Aperture(
            number=aperture_id,
            type=aperture_type,
            size=size,
            **kwargs
        )

        self.apertures[aperture_id] = aperture

        # Generate aperture definition
        if aperture_type == ApertureType.CIRCLE:
            if aperture.hole_diameter:
                cmd = f"%ADD{aperture_id}C,{size}X{aperture.hole_diameter}*%"
            else:
                cmd = f"%ADD{aperture_id}C,{size}*%"

        elif aperture_type == ApertureType.RECTANGLE:
            width = kwargs.get('width', size)
            height = kwargs.get('height', size)
            if aperture.hole_diameter:
                cmd = f"%ADD{aperture_id}R,{width}X{height}X{aperture.hole_diameter}*%"
            else:
                cmd = f"%ADD{aperture_id}R,{width}X{height}*%"

        elif aperture_type == ApertureType.OBROUND:
            width = kwargs.get('width', size)
            height = kwargs.get('height', size)
            cmd = f"%ADD{aperture_id}O,{width}X{height}*%"

        else:
            cmd = f"%ADD{aperture_id}C,{size}*%"

        self.commands.append(cmd)

    def select_aperture(self, aperture_id: int):
        """Select aperture for drawing."""
        self.current_aperture = aperture_id
        self.commands.append(f"D{aperture_id}*")

    def move_to(self, x: float, y: float):
        """Move to position without plotting."""
        x_str = self._format_coordinate(x)
        y_str = self._format_coordinate(y)
        self.commands.append(f"X{x_str}Y{y_str}D02*")

    def plot_to(self, x: float, y: float):
        """Draw line to position."""
        x_str = self._format_coordinate(x)
        y_str = self._format_coordinate(y)
        self.commands.append(f"X{x_str}Y{y_str}D01*")

    def flash(self, x: float, y: float):
        """Flash aperture at position (for pads, vias)."""
        x_str = self._format_coordinate(x)
        y_str = self._format_coordinate(y)
        self.commands.append(f"X{x_str}Y{y_str}D03*")

    def draw_trace(
        self,
        x1: float, y1: float,
        x2: float, y2: float,
        width: float,
        aperture_id: Optional[int] = None
    ):
        """
        Draw trace.

        Args:
            x1, y1: Start coordinates
            x2, y2: End coordinates
            width: Trace width
            aperture_id: Aperture to use (creates if None)
        """
        if aperture_id is None:
            # Create aperture for this width
            aperture_id = self._get_or_create_circle_aperture(width)

        self.select_aperture(aperture_id)
        self.move_to(x1, y1)
        self.plot_to(x2, y2)

    def draw_pad(
        self,
        x: float, y: float,
        diameter: float,
        hole_diameter: Optional[float] = None
    ):
        """Draw pad."""
        aperture_id = self._get_or_create_circle_aperture(
            diameter,
            hole_diameter=hole_diameter
        )

        self.select_aperture(aperture_id)
        self.flash(x, y)

    def draw_rectangle_pad(
        self,
        x: float, y: float,
        width: float,
        height: float,
        hole_diameter: Optional[float] = None
    ):
        """Draw rectangular pad."""
        aperture_id = len(self.apertures) + 10

        self.add_aperture(
            aperture_id,
            ApertureType.RECTANGLE,
            width,
            width=width,
            height=height,
            hole_diameter=hole_diameter
        )

        self.select_aperture(aperture_id)
        self.flash(x, y)

    def draw_polygon(self, points: List[Tuple[float, float]]):
        """Draw filled polygon."""
        if len(points) < 3:
            return

        # Set region mode
        self.commands.append("G36*")

        # Move to first point
        self.move_to(points[0][0], points[0][1])

        # Draw to other points
        for x, y in points[1:]:
            self.plot_to(x, y)

        # Close polygon
        self.plot_to(points[0][0], points[0][1])

        # End region mode
        self.commands.append("G37*")

    def _format_coordinate(self, value: float) -> str:
        """Format coordinate value."""
        # Convert to integer representation
        # For format 6.4: multiply by 10000
        if self.units == "metric":
            # Millimeters with 4 decimal places
            int_value = int(value * 10000)
        else:
            # Inches with 4 decimal places
            int_value = int(value * 10000)

        return str(int_value)

    def _get_or_create_circle_aperture(
        self,
        diameter: float,
        hole_diameter: Optional[float] = None
    ) -> int:
        """Get existing or create new circular aperture."""
        # Check if aperture exists
        for ap_id, aperture in self.apertures.items():
            if (aperture.type == ApertureType.CIRCLE and
                abs(aperture.size - diameter) < 0.001 and
                aperture.hole_diameter == hole_diameter):
                return ap_id

        # Create new aperture
        new_id = len(self.apertures) + 10
        self.add_aperture(new_id, ApertureType.CIRCLE, diameter, hole_diameter=hole_diameter)
        return new_id

    def end_file(self):
        """End Gerber file."""
        self.commands.append("M02*")  # End of file

    def write_to_file(self, filename: str):
        """Write Gerber to file."""
        content = "\n".join(self.commands)

        with open(filename, 'w') as f:
            f.write(content)

        logger.info(f"Gerber file written: {filename}")

    def get_content(self) -> str:
        """Get Gerber file content."""
        return "\n".join(self.commands)


class ExcellonWriter:
    """Write Excellon drill files."""

    def __init__(self, units: str = "metric"):
        """
        Initialize Excellon writer.

        Args:
            units: Units (metric or imperial)
        """
        self.units = units
        self.tools: Dict[int, float] = {}  # tool number -> diameter
        self.holes: List[DrillHole] = []
        logger.info(f"ExcellonWriter initialized ({units})")

    def add_tool(self, tool_number: int, diameter: float):
        """
        Add drill tool.

        Args:
            tool_number: Tool number
            diameter: Drill diameter
        """
        self.tools[tool_number] = diameter

    def add_hole(
        self,
        x: float,
        y: float,
        diameter: float,
        plated: bool = True
    ):
        """
        Add drill hole.

        Args:
            x, y: Coordinates
            diameter: Hole diameter
            plated: Is hole plated
        """
        self.holes.append(DrillHole(x, y, diameter, plated))

    def generate(self) -> str:
        """Generate Excellon drill file."""
        lines = []

        # Header
        lines.append("M48")  # Start of header
        lines.append("; Generated by Circuit.AI")
        lines.append(f"; Date: {datetime.utcnow().isoformat()}")

        # Units
        if self.units == "metric":
            lines.append("METRIC,TZ")
        else:
            lines.append("INCH,TZ")

        # Tool definitions
        # Group holes by diameter
        hole_sizes = set(hole.diameter for hole in self.holes)
        tool_map = {}

        for i, diameter in enumerate(sorted(hole_sizes), start=1):
            lines.append(f"T{i:02d}C{diameter:.3f}")
            tool_map[diameter] = i

        lines.append("%")  # End of header
        lines.append("G90")  # Absolute coordinates
        lines.append("G05")  # Drill mode

        # Group holes by tool
        holes_by_tool = {}
        for hole in self.holes:
            tool_num = tool_map[hole.diameter]
            if tool_num not in holes_by_tool:
                holes_by_tool[tool_num] = []
            holes_by_tool[tool_num].append(hole)

        # Write holes for each tool
        for tool_num in sorted(holes_by_tool.keys()):
            lines.append(f"T{tool_num:02d}")

            for hole in holes_by_tool[tool_num]:
                x_str = f"{hole.x:.4f}"
                y_str = f"{hole.y:.4f}"
                lines.append(f"X{x_str}Y{y_str}")

        lines.append("M30")  # End of program

        return "\n".join(lines)

    def write_to_file(self, filename: str):
        """Write drill file."""
        content = self.generate()

        with open(filename, 'w') as f:
            f.write(content)

        logger.info(f"Drill file written: {filename}")


class PickAndPlaceWriter:
    """Generate pick-and-place files."""

    def __init__(self):
        """Initialize pick-and-place writer."""
        self.components: List[Component] = []

    def add_component(
        self,
        designator: str,
        x: float, y: float,
        rotation: float,
        side: str,
        part_number: str,
        value: str,
        package: str
    ):
        """Add component."""
        self.components.append(Component(
            designator=designator,
            x=x, y=y,
            rotation=rotation,
            side=side,
            part_number=part_number,
            value=value,
            package=package
        ))

    def generate_csv(self) -> str:
        """Generate CSV format."""
        lines = []

        # Header
        lines.append("Designator,X,Y,Rotation,Side,PartNumber,Value,Package")

        # Components
        for comp in self.components:
            lines.append(
                f"{comp.designator},{comp.x:.4f},{comp.y:.4f},"
                f"{comp.rotation:.2f},{comp.side},"
                f"{comp.part_number},{comp.value},{comp.package}"
            )

        return "\n".join(lines)

    def write_to_file(self, filename: str):
        """Write pick-and-place file."""
        content = self.generate_csv()

        with open(filename, 'w') as f:
            f.write(content)

        logger.info(f"Pick-and-place file written: {filename}")


class GerberValidator:
    """Validate Gerber files."""

    def __init__(self):
        """Initialize validator."""
        logger.info("GerberValidator initialized")

    def validate_file(self, filename: str) -> Dict[str, Any]:
        """
        Validate Gerber file.

        Args:
            filename: Gerber file path

        Returns:
            Validation results
        """
        errors = []
        warnings = []

        try:
            with open(filename, 'r') as f:
                content = f.read()

            # Check for required headers
            if "%FSLAX" not in content:
                errors.append("Missing format specification (%FSLAX)")

            if "%MO" not in content:
                warnings.append("Missing units specification (%MOMM or %MOIN)")

            # Check for aperture definitions
            if "%ADD" not in content:
                errors.append("No aperture definitions found")

            # Check for end of file marker
            if "M02*" not in content:
                warnings.append("Missing end of file marker (M02*)")

            # Validate aperture references
            defined_apertures = self._extract_apertures(content)
            used_apertures = self._extract_used_apertures(content)

            undefined_used = used_apertures - defined_apertures
            if undefined_used:
                errors.append(f"Undefined apertures used: {undefined_used}")

            # Check coordinate format
            if not self._validate_coordinates(content):
                errors.append("Invalid coordinate format detected")

        except Exception as e:
            errors.append(f"Error reading file: {e}")

        return {
            'valid': len(errors) == 0,
            'errors': errors,
            'warnings': warnings,
            'file': filename
        }

    def _extract_apertures(self, content: str) -> set:
        """Extract defined apertures."""
        import re

        apertures = set()
        pattern = r'%ADD(\d+)'

        for match in re.finditer(pattern, content):
            apertures.add(int(match.group(1)))

        return apertures

    def _extract_used_apertures(self, content: str) -> set:
        """Extract used apertures."""
        import re

        apertures = set()
        pattern = r'D(\d+)\*'

        for match in re.finditer(pattern, content):
            ap_num = int(match.group(1))
            # D01, D02, D03 are commands, not apertures
            if ap_num > 3:
                apertures.add(ap_num)

        return apertures

    def _validate_coordinates(self, content: str) -> bool:
        """Validate coordinate format."""
        import re

        # Look for coordinate commands
        pattern = r'X([-\d]+)Y([-\d]+)'

        matches = re.findall(pattern, content)

        if not matches:
            return True  # No coordinates to validate

        # Check that all coordinates have consistent length
        x_lengths = set(len(match[0]) for match in matches)
        y_lengths = set(len(match[1]) for match in matches)

        # Should have consistent format
        return len(x_lengths) <= 2 and len(y_lengths) <= 2


class GerberPackageGenerator:
    """Generate complete Gerber package."""

    def __init__(self, output_dir: str):
        """
        Initialize package generator.

        Args:
            output_dir: Output directory
        """
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"GerberPackageGenerator initialized: {output_dir}")

    async def generate_package(
        self,
        pcb_data: Dict[str, Any],
        project_name: str
    ) -> Dict[str, str]:
        """
        Generate complete Gerber package.

        Args:
            pcb_data: PCB design data
            project_name: Project name

        Returns:
            Dictionary of generated files
        """
        generated_files = {}

        # Generate top copper
        top_copper_file = self.output_dir / f"{project_name}.gtl"
        top_writer = GerberWriter(units="metric")
        self._generate_copper_layer(top_writer, pcb_data, 'top')
        top_writer.write_to_file(str(top_copper_file))
        generated_files['top_copper'] = str(top_copper_file)

        # Generate bottom copper
        bottom_copper_file = self.output_dir / f"{project_name}.gbl"
        bottom_writer = GerberWriter(units="metric")
        self._generate_copper_layer(bottom_writer, pcb_data, 'bottom')
        bottom_writer.write_to_file(str(bottom_copper_file))
        generated_files['bottom_copper'] = str(bottom_copper_file)

        # Generate drill file
        drill_file = self.output_dir / f"{project_name}.drl"
        drill_writer = ExcellonWriter(units="metric")
        self._generate_drill_file(drill_writer, pcb_data)
        drill_writer.write_to_file(str(drill_file))
        generated_files['drill'] = str(drill_file)

        # Generate pick-and-place
        pnp_file = self.output_dir / f"{project_name}_pnp.csv"
        pnp_writer = PickAndPlaceWriter()
        self._generate_pick_and_place(pnp_writer, pcb_data)
        pnp_writer.write_to_file(str(pnp_file))
        generated_files['pick_and_place'] = str(pnp_file)

        logger.info(f"Generated {len(generated_files)} Gerber files")

        return generated_files

    def _generate_copper_layer(
        self,
        writer: GerberWriter,
        pcb_data: Dict[str, Any],
        side: str
    ):
        """Generate copper layer."""
        writer.start_file()

        # Draw traces
        traces = pcb_data.get('traces', [])
        for trace in traces:
            if trace.get('layer') == side:
                writer.draw_trace(
                    trace['x1'], trace['y1'],
                    trace['x2'], trace['y2'],
                    trace['width']
                )

        # Draw pads
        pads = pcb_data.get('pads', [])
        for pad in pads:
            if pad.get('layer') == side:
                if pad.get('shape') == 'circle':
                    writer.draw_pad(
                        pad['x'], pad['y'],
                        pad['diameter'],
                        pad.get('hole_diameter')
                    )
                elif pad.get('shape') == 'rectangle':
                    writer.draw_rectangle_pad(
                        pad['x'], pad['y'],
                        pad['width'], pad['height'],
                        pad.get('hole_diameter')
                    )

        writer.end_file()

    def _generate_drill_file(
        self,
        writer: ExcellonWriter,
        pcb_data: Dict[str, Any]
    ):
        """Generate drill file."""
        holes = pcb_data.get('holes', [])

        for hole in holes:
            writer.add_hole(
                hole['x'], hole['y'],
                hole['diameter'],
                hole.get('plated', True)
            )

    def _generate_pick_and_place(
        self,
        writer: PickAndPlaceWriter,
        pcb_data: Dict[str, Any]
    ):
        """Generate pick-and-place file."""
        components = pcb_data.get('components', [])

        for comp in components:
            writer.add_component(
                comp['designator'],
                comp['x'], comp['y'],
                comp.get('rotation', 0),
                comp.get('side', 'top'),
                comp.get('part_number', ''),
                comp.get('value', ''),
                comp.get('package', '')
            )


# Singleton instances
gerber_validator = GerberValidator()
